name: Install dependencies an Lint check

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Lint 🔧
        run: |
          npm install
          npm run lint:js
